root: 'statics.hello'
list:
  - 'statics.hello'
  - 'statics.send'
  - 'passwords.new'
  - 'passwords.valid'
  - 'articles.list'
  - 'articles.show'
  - 'articles.new'
  - 'articles.edit'
  - 'articles.create'
  - 'articles.update'
  - 'articles.destroy'
  - 'events.list'
  - 'courses.list'

not_found: 'statics.not-found'